# Arda CLI Configuration File
#
# This file contains the default configuration for Arda CLI.
# Themes can be found by running: arda theme --list

[theme]
# Default theme to use for the CLI
# Options: dracula, forest, solarized, nord, quartz, star, cargo, etc.
# You can also use variants: -slim, -modern, -nu, -robo
default = "dracula"

[output]
# Additional output settings can be added here in the future
# verbose = false
# timestamp = false
